language: go
sudo: required
addons:
  hostname: testing
  hosts:
    - testing
  apt:
    packages:
      - net-tools
      - iproute2
services: docker
go_import_path: github.com/camptocamp/bivac
go:
  - "1.12"
before_install:
  - export INTERNAL_IP=$(ip -o -4 addr show dev `ls /sys/class/net | grep -E "^eth|^en" | head -n 1` | cut -d' ' -f7 | cut -d'/' -f1)
  - export CATTLE_HOSTNAME=testing
  - sudo sed -i "s/\DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry=${INTERNAL_IP}:5000 /g" /etc/default/docker
  - sudo cat /etc/default/docker
  - sudo service docker restart
install:
  - go get github.com/bradfitz/goimports
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - build-binary
  - build-docker-image
  - coverage
  - integration-tests/docker
  - integration-tests/cattle
jobs:
  include:
    - stage: build-binary
      script: make
    - stage: build-docker-image
      script: docker build .
    - stage: coverage
      if: repo = camptocamp/bivac
      script:
        - make test
        - "$HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage"
    - stage: integration-tests/docker
      script:
        - ./test/integration/docker/prepare.sh
        - docker build -t $INTERNAL_IP:5000/bivac-testing .
        - docker push $INTERNAL_IP:5000/bivac-testing
        - run-parts -v test/integration/docker/tests -a $INTERNAL_IP:5000/bivac-testing -a debug
    - stage: integration-tests/cattle
      script:
        - sudo sed -i 's/localhost/testing localhost/g' /etc/hosts
        - ./test/integration/cattle/prepare.sh
        - docker build -t $INTERNAL_IP:5000/bivac-testing .
        - docker push $INTERNAL_IP:5000/bivac-testing
        - run-parts -v test/integration/cattle/tests -a $INTERNAL_IP:5000/bivac-testing -a debug
